version: "3.9"
services:
  db:
    image: mysql:8.3.0
    volumes:
      - ./backend/mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "flashcard_db"
      MYSQL_USER: "tahara-y"
      MYSQL_PASSWORD: "Nttpc123"
      MYSQL_ROOT_PASSWORD: "Nttpc123"
    container_name: db_container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backend-container
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    command: yarn start
    ports:
      - "3001:3000"
    container_name: frontend-container
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: . # プロジェクトのルートディレクトリをビルドコンテキストに設定
      dockerfile: ./Dockerfile # nginxディレクトリ内のDockerfileを指定
    ports:
      - "80:80"
    container_name: nginx-container
    depends_on:
      - backend
