# Generated by Django 4.2.5 on 2023-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False),
                ),
                ("word", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
    ]
