# Generated by Django 4.2.6 on 2023-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcard_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="id",
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
