# Generated by Django 4.2.6 on 2023-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcard_api", "0002_alter_flashcard_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="id",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False),
        ),
    ]
