# Generated by Django 4.2.6 on 2024-01-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcard_api", "0004_chapternumber_flashcard_chapter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapternumber",
            old_name="chapter",
            new_name="chapterId",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="current_chapter",
            new_name="currentChapter",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="last_word_id",
            new_name="currentId",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="previous_chapter",
        ),
        migrations.AddField(
            model_name="chapternumber",
            name="chapterName",
            field=models.CharField(default="章の名前を入力してください", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="currentChapterWordOrder",
            field=models.CharField(default="00001", max_length=5),
        ),
    ]
