# Generated by Django 4.2.6 on 2024-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcard_api", "0005_rename_chapter_chapternumber_chapterid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapternumber",
            name="chapterName",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="currentId",
            field=models.IntegerField(default=0),
        ),
    ]
